name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
      full-test:  
        runs-on: ubuntu-20.04
        steps:
          - name: Clean diskspace
            run: |
              df -h;
              sudo apt-get update;
              sudo apt-get remove --purge --autoremove --yes \
                dotnet* mono* libmono* temurin* powershell \
                libruby* ruby* php7* php8* hhvm \
                llvm* libllvm* clang* libclang* \
                azure* google-cloud* apache2* podman* kubectl \
                microsoft-edge* google-chrome* firefox \
                mongodb* mysql* libmysql* \
                r-base* r-cran* r-doc* r-recommended;
              sudo apt-get clean;
              sudo rm -rf \
                /etc/{mono,mysql,php} \
                /opt/{az,microsoft} \
                /usr/lib/{heroku,R} \
                /usr/local/lib/{android,node_modules} \
                /usr/local/share/{powershell,chromium} \
                /usr/share/{dotnet,kotlinc,miniconda,php,swift} /usr/share/az_*;
              df -h
          - uses: actions/checkout@v3
            with:
              clean: false
              submodules: 'recursive'
          - uses: webfactory/ssh-agent@v0.5.4
            with:
                 ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run build
            timeout-minutes: 600
            run: |
               docker run --rm \
                 -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent \
                 -e GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./build.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
          - name: Run full test
            timeout-minutes: 15
            run: |
               docker run --rm \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./full-test.sh
